templates01/tempapp01/urls.py
from django.urls import path
from tempapp01 import views

# Template tagging
app_name = 'tempapp01'

urlpatterns = [
    path('', views.index, name='index'),
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),


]

templates01/templates01/urls.py
from django.contrib import admin
from django.urls import path, include
from tempapp01 import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('tempapp01/', include('tempapp01.urls')),
]

templates01/tempapp01/models.py
from django.db import models

# Create your models here.

templates01/tempapp01/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    context_dict = {'text': "Hello world!", 'number': 100}
    return render(request, 'tempapp01/index.html', context = context_dict)

def other(request):
    return render(request, 'tempapp01/other.html')

def relative(request):
    return render(request, 'tempapp01/rel_url_templ.html')

templates01/tempapp01/templates/tempapp01/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <title>Base template</title>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <div class="navbar-nav">
          <a class="navbar-brand" href="{% url 'index' %}">BRAND LOGO</a>
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          <a class="nav-link" href="{% url 'tempapp01:other' %}">Other</a>
          <a class="nav-link" href="{% url 'tempapp01:relative' %}">Relative URL Templates</a>
        </div>
      </div>
    </nav>
    <div id="pagecontainer" class="container" >
      {% block body_block %}
      <!-- Anything outsite of this will be inherited if we call extend on it -->
      {% endblock %}
    </div>
    <script type="text/javascript">
      $("#pagecontainer").css('padding-top', $('nav.navbar').css('height'));
    </script>
  </body>
</html>

templates01/tempapp01/templates/tempapp01/index.html
<!DOCTYPE html>
{% extends "tempapp01/base.html" %}
{% load custom_filters %}
  {% block body_block %}
    <h1>Welcome to Index</h1>
    <h3>This is index/html showing - extended from base.html</h3>
    <a href="{% url 'tempapp01:relative' %}">Go to the original Relative URLs View</a>

    <h2>Template filters</h2>
    <p>{{ text|upper }}</p>
    <p>{{ text|strcut:"o" }}</p>
    <p>{{ number|add:"99" }}</p>
  {% endblock %}

templates01/tempapp01/templates/tempapp01/other.html
<!DOCTYPE html>
{% extends "tempapp01/base.html" %}
  {% block body_block %}
    <h1>Welcome to Other</h1>
    <h2>This is an example of template inheritance!</h2>
    <a href="{% url 'tempapp01:index' %}">Back to Index view</a>
  {% endblock %}

templates01/tempapp01/templates/tempapp01/rel_url_templ.html
<!DOCTYPE html>
{% extends "tempapp01/base.html" %}
  {% block body_block %}
    <h1>Welcome to Relative URL Templates</h1>
    <p><a href="{% url 'tempapp01:other' %}">Link to Other view</a></p>
    <p><a href="{% url 'admin:index'%}">Link to Admin Index page</a></p>
    <p><a href="{% url 'index' %}">Link to Home index page</a></p>
  {% endblock %}